# Generated by Django 5.0.2 on 2024-07-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_livro"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AddField(
            model_name="livro",
            name="categoria",
            field=models.ForeignKey(
                default=4, on_delete=django.db.models.deletion.PROTECT, related_name="livros", to="core.categoria"
            ),
            preserve_default=False,
        ),
    ]
