# Generated by Django 5.0.2 on 2024-07-30 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_livro_eidtora_alter_livro_categoria"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="eidtora",
            new_name="editora",
        ),
        migrations.AddField(
            model_name="livro",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros",
                to="core.autor",
            ),
        ),
    ]
